name: Release Server
on:
  push:
    tags: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.200
    - name: Build
      run: |
        ver=${GITHUB_REF#refs/tags/}
        res=$(echo $ver | sed 's/-rc/./g')  
        dotnet build --configuration Release /p:AssemblyVersion=$res
    - name: Test
      run: dotnet test --no-build --configuration Release 

    - name: Publish Server
      run: dotnet publish --no-build ./MyServiceBus.Persistence.Server/MyServiceBus.Persistence.Server.csproj --output ./publish-api --configuration Release 

    - name: ls
      run: ls ./publish-api
      
    - name: Publish Server to Registry
      uses: myjettools/Publish-Docker-Github-Action@master
      with:
        name: myjettools/my-service-bus-persistence
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./publish-api
        # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
        tag_names: true  

